#!/bin/bash
set -e

FILE_CERTIFICADOS=adecco.cert
FECHA=`date +%Y%m%d`

source config.sh
source functions.sh

function logAdecco() {
	echo '[INFO]' $@
}

function logAdeccoInline() {
	while read r
	do
		logAdecco "$r"
	done
}

function main() {
	logAdecco "Eliminando archivos de certificados anteriores locales"
	rm -f *.crt

	logAdecco "Leyendo certificados de $FILE_CERTIFICADOS"
	awk -f actualizarAFIP.awk $FILE_CERTIFICADOS

	logAdecco "Haciendo backups de certificados"
	backupCertificados

	logAdecco "Enviando nuevos certificados al servidor"
	enviarCertificados

	logAdecco "Importando Certificados en el almacen"
	importarCertificados
}

function backupCertificados() {
	for i in $CUITSADECCO; do
		CERT=$CERTPATH/$i.crt 
		mv $CERT $CERT.$FECHA
	done
}

function enviarCertificados() {
	for i in $CUITSADECCO; do
		CERT=$CERTPATH/$i.crt 
		mv $i.crt $CERT
	done
}

function importarCertificados() {
	cp $KS $KS.$FECHA
	for i in $CUITSADECCO; do
		saveCertificate $i $CERTPATH/$i.crt $KS 2>&1 | logAdeccoInline
	done
}

######
main #
######
