#!/bin/bash
set -e

source config.sh
source functions.sh

function importCertificate() {
	getCertificate $1 443 > $1.cert
	saveCertificate $1 $1.cert $3
}

for i in $SERVERS
do
	importCertificate $i
done

